---
title: "Experiment"
output: html_document
---

```{r, results = "hide"}
set.seed(123)
library(tidyverse)
files <- list.files("Heston_Standard", 
                    pattern = "\\.R$", 
                    full.names = TRUE)
lapply(files, source)

source("Param_Est/R_Est.R")

```


Parameter Set up
```{r}
d <- 3
T <- 1
N <- 252
x0 <- c(0.015, 0.020, 0.025)
nstates <- 2
dt <- 1/252 

Gamma1 <- matrix(c(0.99, 0.01, 0.01, 0.99), 2,2, byrow=TRUE)
Gamma2 <- matrix(c(0.99, 0.01, 0.01, 0.99), 2,2, byrow=TRUE)
Gamma3 <- matrix(c(0.99, 0.01, 0.01, 0.99), 2,2, byrow=TRUE)


Gamma_list <- list(Gamma1, Gamma2, Gamma3)

Reg <- simulate_Regime_multi(Gamma_list, N = 252, init_state = 0)

# same change of magnitude, for each x
param_mat <- rbind(
  # regime 1 (calm)
  c(10.0, 0.10, 0.05),  # x1
  c(9.5,  0.11, 0.05),  # x2 slightly perturbed
  c(10.5, 0.09, 0.05),  # x3 slightly perturbed
  
  # regime 2 (turbulent)
  c(5.0,  0.50, 0.05),  # x1
  c(4.8,  0.51, 0.05),  # x2
  c(5.2,  0.49, 0.05)   # x3
)
colnames(param_mat) <- c("kappa","theta","sigma")

R <- matrix(c(
  1, 0.60, 0.40,
  0.60, 1, 0.70,
  0.40, 0.70, 1
), 3, 3, byrow = TRUE)

alpha0 <- 0.001
alpha  <- c(0.8, 0.5, 0.3)
```


Simulation
```{r}
sim <- simulate_CIR_dependent(
  x0 = x0, Reg_series = Reg, param_mat = param_mat,
  T = T, N = N, M = 1,
  interp = FALSE, R = R,
  alpha0 = alpha0, alpha = alpha
)

X <- sim$X_paths
r <- sim$r_paths
plot_multi_series(Reg)
plot_multi_series(X)
plot(r, type = 'l')
```


Vector form Get_init
```{r}
init <- initial_heuristic_multi(X, states = 2, dt = 1/252)
plot_multi_series(init$cluster)
plot_multi_series(Reg)
init$reg_param
init$Gamma_list
init$R_hat
R
```




```{r}

kappa1 <- cbind(param_mat[1,1], param_mat[4,1])
theta1 <- cbind(param_mat[1,2], param_mat[4,2])
sigma1 <- cbind(param_mat[1,3], param_mat[4,3])

kappa2 <- cbind(param_mat[2,1], param_mat[5,1])
theta2 <- cbind(param_mat[2,2], param_mat[5,2])
sigma2 <- cbind(param_mat[2,3], param_mat[5,3])

kappa3 <- cbind(param_mat[3,1], param_mat[6,1])
theta3 <- cbind(param_mat[3,2], param_mat[6,2])
sigma3 <- cbind(param_mat[3,3], param_mat[6,3])


# Process 1
plot_single_viterbi(X[1,], nstates, Gamma1, kappa1, theta1, sigma1, Reg[1,], "X1")

# Process 2
plot_single_viterbi(X[2,], nstates, Gamma2, kappa2, theta2, sigma2, Reg[2,], "X2")

# Process 3
plot_single_viterbi(X[3,], nstates, Gamma3, kappa3, theta3, sigma3, Reg[3,], "X3")




```



```{r}

start_date <- as.Date("2024-01-01")
date_sequence <- seq(from = start_date, by = "day", length.out = N+1)
    

X1_BW_res <- baum_welch_single_analysis(
  X_series = X[1,],         
  Reg_chain = Reg[1,],      
  date_sequence = date_sequence,
  nstates = 2,
  runs = 10,
  dt = 1/252,
  interval_step = 10,
  subtitle_text = "X1"
)


X2_BW_res <- baum_welch_single_analysis(
  X_series = X[2,],         
  Reg_chain = Reg[2,],      
  date_sequence = date_sequence,
  nstates = 2,
  runs = 10,
  dt = 1/252,
  interval_step = 10,
  subtitle_text = "X2"
)



X3_BW_res <- baum_welch_single_analysis(
  X_series = X[3,],         
  Reg_chain = Reg[3,],      
  date_sequence = date_sequence,
  nstates = 2,
  runs = 10,
  dt = 1/252,
  interval_step = 10,
  subtitle_text = "X3"
)
```




```{r}
X1_BW_res$params
X2_BW_res$params
X3_BW_res$params
```

```{r}
params_list <- list(X1_BW_res$params, X2_BW_res$params, X3_BW_res$params)
states_list <- list(X1_BW_res$states_estimate, X2_BW_res$states_estimate, X3_BW_res$states_estimate)

outR <- estimate_R_sample_from_BW(
  X = X, 
  params_list = params_list,
  states_list = states_list,
  dt = 1/252
)

outR$R_hat
```













